name: CI

on: [push]
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0

    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x   

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup Azure Service Bus namespace for testing
      uses: azure/CLI@v1
      with:
        azcliversion: 2.21.0
        inlineScript: |
          az servicebus namespace create --name $GITHUB_SHA --resource-group AzureServiceBusGithubActionsTest --location westeurope --tags CommitSHA=$GITHUB_SHA --sku Standard
          echo "AZURESERVICEBUS_CONNECTIONSTRING=$(az servicebus namespace authorization-rule keys list --resource-group AzureServiceBusGithubActionsTest --namespace-name $GITHUB_SHA --name RootManageSharedAccessKey --query primaryConnectionString --output tsv)" >> $GITHUB_ENV
          
    - name: Build
      run: dotnet build --configuration Release

    - name: Run
      run: dotnet run --configuration Release --no-build --no-restore

    - name: Teardown Azure Service Bus namespace for testing
      uses: azure/CLI@v1
      if: ${{ always() }}
      with:
        azcliversion: 2.21.0
        inlineScript: |
          az servicebus namespace delete --name $GITHUB_SHA --resource-group AzureServiceBusGithubActionsTest
