name: CI

on: [push]
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0

    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x   

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup Azure Service Bus namespace for testing
      id: setup-asb-namespace
      uses: azure/CLI@v1
      with:
        azcliversion: 2.21.0
        inlineScript: |
          asbnamespace=ATT${GITHUB_SHA:0:7}
          echo "::set-output name=azureservicebus-namespace::$asbnamespace"
          asbresourcescreated=$(az servicebus namespace create --name $ --resource-group AzureServiceBusGithubActionsTest --location westeurope --tags CommitSHA=$GITHUB_SHA Actor=$GITHUB_ACTOR Repository=$GITHUB_REPOSITORY --sku Standard)
          echo "::add-mask::$asbresourcescreated"
          asbconnectionstring=$(az servicebus namespace authorization-rule keys list --resource-group AzureServiceBusGithubActionsTest --namespace-name $asbnamespace --name RootManageSharedAccessKey --query primaryConnectionString --output tsv)
          echo "::add-mask::$asbconnectionstring"
          echo "::set-output name=azureservicebus-connection-string::$asbconnectionstring"
          
    - name: Build
      run: dotnet build --configuration Release

    - name: Run
      run: dotnet run --configuration Release --no-build --no-restore
      env: 
        AZURESERVICEBUS_CONNECTIONSTRING: ${{ steps.setup-asb-namespace.outputs.azureservicebus-connection-string }}

    - name: Teardown Azure Service Bus namespace for testing
      uses: azure/CLI@v1
      if: ${{ always() }}
      with:
        azcliversion: 2.21.0
        inlineScript: |
          az servicebus namespace delete --name ${{ steps.setup-asb-namespace.outputs.azureservicebus-namespace }} --resource-group AzureServiceBusGithubActionsTest
